### PR TITLE
fix usb auto mount

### LINKED ISSUE #60: USB automount doesn't work
#### Describe the bug

USB automount doesn't work in the latest release, as a result, offline music playback can't be tested.

### PR DESCRIPTION
**Pull request by alok760**
Fixes #60

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [x] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [ ] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
After changing release to use Raspbian buster, USB automount stopped working.
#### Changes proposed in this pull request:
Fix USB automount.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -755,8 +755,7 @@ if [ $targetSystem = raspi ]
 then
     echo "Preparing USB automount"
     # systemd-udevd creates its own filesystem namespace, so mount is done, but it is not visible in the principal namespace.
-    sudo mkdir /etc/systemd/system/systemd-udevd.service.d/
-    echo -e "[Service]\nMountFlags=shared" | sudo tee /etc/systemd/system/systemd-udevd.service.d/mountFlagOverride.conf
+    sudo sed -i -e '/^PrivateMounts/ s/yes/no/' /lib/systemd/system/systemd-udevd.service
```
Comment (norbusan) [inline install.sh]: Does the override mechanism not work anymore? Wouldn't
```
echo -e "[Service]\nPrivateMounts=no" | sudo tee /etc/systemd/system/systemd-udevd.service.d/udev-service-override.conf
```
work, too? It would allow us to NOT change system files that will get updated with the next systemd package update.

WDYT?

Comment (alok760) [reply install.sh]: ah, My bad
I was so indulged in finding why it was not working, I totally forgot about the override method.
updated the PR now.
Thank You @hongquan and @norbusan

Comment (norbusan) [reply install.sh]: Thanks for the update

**Comment by norbusan** [comment]
Thanks, merged
