### PR TITLE
install usbmount

### LINKED ISSUE #20: Enable USB automount
#### Describe the bug
- raspbian lite(on which susibian is based) doesn't automount USB drives.
- Mounting is required in order for the media-daemon to work for USB audio playback 

#### Expected behaviour
- Automount USB drives

### PR DESCRIPTION
**Pull request by alok760**
Fixes #20

#### Checklist

- [x] I have read the Contribution & Best practices Guide and my PR follows them.
- [x] My branch is up-to-date with the Upstream master branch.
- [ ] The unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] All the functions created/modified in this PR contain relevant docstrings.

#### Test Passing

- [x] The SUSI Server must be building on the pi on bootup
- [x] The hotword detection should have a decent accuracy
- [ ] SUSI Linux shouldn't crash when switching from online to offline and vice versa (failing as of now)
- [ ] SUSI Linux should be able to boot offline when no internet connection available (failing)

#### Short description of what this resolves:
Raspbian lite(on which susibian is based) doesn't automount USB drives, Mounting is required in order for the media-daemon to work for USB audio playback. Added usbmount to mount usb drives automatically.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -695,6 +696,7 @@ if [ $targetSystem = raspi ]
 then
     echo "Updating the Udev Rules"
     sudo bash $INSTALLERDIR/raspi/media_daemon/media_udev_rule.sh
+    sudo sed -i 's/slave/shared/' /lib/systemd/system/systemd-udevd.service
```
Comment (norbusan) [inline install.sh]: What does this do? And why is it necessary? It is somehow surprising

Comment (alok760) [reply install.sh]: systemd-udevd creates its own filesystem namespace, so mount is done, but it is not visible in the principal namespace. Thus changing `MountFlags=slave` to `MountFlags=shared`.

Comment (alok760) [reply install.sh]: Updated the PR, Thanks for the suggestions

Comment (norbusan) [reply install.sh]: Thanks for the info, I now read up on it, indeed. 

**BUT** Please don't change system files, please use the later approach mentioned here https://unix.stackexchange.com/questions/330094/udev-rule-to-mount-disk-does-not-work/330156#330156 the one where an override.conf is created. Thanks!

Comment (alok760) [reply install.sh]: I've done the mentioned changes, please review.

**Comment by norbusan** [comment]
Thanks for the update, looks fine

**Comment by norbusan** [comment]
@alok760 When you think it is ready please remove the draft status and re-request review. Thanks

**Comment by hongquan** [comment]
Why do you use `usbmount`? For job like this, [udisks](https://wiki.archlinux.org/index.php/Udisks) is more mainstream in Linux world.

**Comment by norbusan** [comment]
udisks is nice, but getting it to work **without** a user session (we don't have a user session running on the RPi) is a pain. If you have a good idea, please share it. But all this polkit etc stuff smells a lot like loads of complications to me.

**Comment by hongquan** [comment]
Ok. If you are afraid of handling config files needed by udisks, we can delay udisks task. The direction now is to fix "media_daemon" instead, and drop `usbmount` (because media_daemon already takes care the mounting job).

But, if we want to make easier integration with desktop, "udisks" is still the way to go.

**Comment by norbusan** [comment]
I have already reverted the usbmount commit, and send a partial fix for media daemon, more work and testing is necessary, because the directory structure has changed completely.
